version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=picsshare2
      - DB_USERNAME=admin
      - DB_PASSWORD=password
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: picsshare2
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
